# Generated by Django 5.0.6 on 2024-06-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yname', models.CharField(blank=True, max_length=100, null=True)),
                ('Yemail', models.CharField(blank=True, max_length=100, null=True)),
                ('Yphone', models.IntegerField(blank=True, null=True)),
                ('Ymessage', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
