# Generated by Django 5.0.6 on 2024-06-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_userdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='Usercpassword',
            new_name='UserCpassword',
        ),
        migrations.RenameField(
            model_name='userdb',
            old_name='Userpassword',
            new_name='UserPassword',
        ),
    ]
