# Generated by Django 5.0.6 on 2024-07-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_usercpassword_userdb_usercpassword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(blank=True, max_length=100, null=True)),
                ('Productprice', models.IntegerField(blank=True, null=True)),
                ('Productquantity', models.IntegerField(blank=True, null=True)),
                ('Totalprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
