# Generated by Django 5.0.6 on 2024-07-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_cartdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Productprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
